spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

# 커스텀 설정(Spring 내부 설정 아님)
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes
  #        show_sql: true
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0

#cloud:
#  aws:
#    s3:
#      bucket:
#    credentials:
#      access-key:
#      secret-key:
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false
#    # multipartFile 용량 늘려주는 설정
#    spring:
#      servlet:
#        multipart:
#          max-file-size: 10MB
#          max-request-size: 10MB
