spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
#  sql:
#    init:
#      mode: always

# 커스텀 설정(Spring 내부 설정 아님)
jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaes
  #        show_sql: true
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.example.myapp: DEBUG
#  file:
#    name: app.log
